[package]
name = "my_first_opengl_game"
version = "0.0.1"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.59.0"
image = "0.25.5"
meval = "0.2.0"
noise = "0.9.0"
rand = "0.9.0"
spin_sleep = "1.3.0"
